name: Upload To IDF Component Registry

on: 
  release:
    types: [published, deleted]

jobs: 
  upload:
    name: upload_to_idf_component_registry
    runs-on: ubuntu-latest
    env:
      IDF_COMPONENT_API_TOKEN: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get Component Version
        id: get-version
        run: echo "VERSION=$(python ./ci/get-version.py ./idf_component.yml)" >> "$GITHUB_OUTPUT"

      - name: Install IDF Component Manager
        run: pip install --upgrade idf-component-manager
      
      - name: Show IDF Component Manager Version
        run: pip show idf-component-manager
      
      - name: Upload Component
        if: github.event.action == 'published'
        run: >
          compote component upload --namespace augtons --name FreeRTOS-Cpp
          --allow-existing --version ${{ steps.get-version.outputs.VERSION }}
        
      - name: Delete Component
        if: github.event.action == 'deleted'
        run: >
          compote component delete --namespace augtons --name FreeRTOS-Cpp
          --version ${{ steps.get-version.outputs.VERSION }}
